export const LOGIN = 'LOGIN'
export const GET_USER_INFO = 'GET_USER_INFO'
export const LOGOUT = 'LOGOUT'
export const GET_CHANNEL_LIST = 'GET_CHANNEL_LIST'
export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
